name: Dockerhub-release

env:
  IMAGE_NAME: antlafarge/webscraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 1 * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: retag dev to latest
        run: |
          docker pull ${{ env.IMAGE_NAME }}:dev
          docker buildx imagetools create ${{ env.IMAGE_NAME }}:dev -t ${{ env.IMAGE_NAME }}:latest
      - name: Logout from Docker Hub
        run: docker logout
